### ISSUE TITLE
Título mal escrito

### ISSUE THREAD

**Issue by IgleDev** [PiterWeb/web_proyecto_nuria#1]
La palabra 'desaoga' está mal escrita, sería desahoga. Esta muy chula la página:)!
![Captura de pantalla 2024-01-22 171409](https://github.com/PiterWeb/web_proyecto_nuria/assets/72018196/75d5f428-3134-442e-993f-e65f2d82cbf1)

**Comment by PiterWeb** [comment]
Gracias Igle, agradecido con la corrección.
Cuando pueda la arreglaré

**Comment by PiterWeb** [comment]
Ya está corregido en el siguiente commit [1446aa6](https://github.com/PiterWeb/web_proyecto_nuria/commit/1446aa6e256961a72512aceee8aaafb461432e88)
